### ISSUE TITLE
Use of deprecated set-output command

### ISSUE THREAD

**Issue by anbonifacio** [wowjeeez/rust-conf-read#1]
Hello,
when I run my actions that use rust-conf-read on GitHub, they gives me this warning:

The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by wowjeeez** [comment]
Hey!
Thank you for raising this, I will open a PR in the next few days to address this.

**Comment by wowjeeez** [comment]
@anbonifacio hey man, I know my few days promise took a tad bit more than a few days, but its now fixed lmao. Have a nice day

**Comment by anbonifacio** [comment]
@wowjeeez thank you :) When will be released the new version with the fix? On the actions marketplace I still see 1.0.2 as latest available version.

**Comment by wowjeeez** [comment]
Done!
